# Generated by Django 5.1.7 on 2025-04-10 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='items',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AddField(
            model_name='items',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.OneToOneField(default='0000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
