# Generated by Django 5.1.7 on 2025-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imagewithcaption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithcaption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
