# Generated by Django 5.1.7 on 2025-12-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_visible',
        ),
    ]
