# Generated by Django 5.2.17 on 2026-10-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_coupon_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='order_order_user_id_26e491_idx',
            old_name='order_order_user_id_5a7e9b_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_order_order_s_508a9f_idx',
            old_name='order_order_status_4d7a4b_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
